(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Composite Higgs with pseudoscalar",
  Authors -> {"L. Mason"},
  Version -> "1.4.6",
  Date -> "26. 04. 2019",
  Institutions -> {"SA-CERN"},
  Emails -> {"lara.mason@live.com"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NoBlockName[FRBlock], 0}, {Gamma5[1, 3] -> 1, 0}, {Gamma5[1, 4] -> 0, 0}, {Gamma5[2, 1] -> 0, 0}, {Gamma5[2, 2] -> 0, 0}, {Gamma5[2, 3] -> 0, 0}, {Gamma5[2, 4] -> 1, 0}, {Gamma5[3, 1] -> 1, 0}, {Gamma5[3, 2] -> 0, 0}, {Gamma5[3, 3] -> 0, 0}, {Gamma5[3, 4] -> 0, 0}, {Gamma5[4, 1] -> 0, 0}, {Gamma5[4, 2] -> 1, 0}, {Gamma5[4, 3] -> 0, 0}, {Gamma5[4, 4] -> 0, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} },

S[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "sc",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Msc,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MH[ ___ ] := MH;
Msc[ ___ ] := Msc;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[1] , S[1] , S[1] ] == {{I*gc2, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[4] , S[4] ] == {{0, 0}, {I*gc3, 0}, {0, 0}, {0, 0}},

C[ S[4] , V[1] , V[1] ] == {{I*gc4, 0}, {0, 0}},

C[ S[4] , V[1] , V[2] ] == {{I*gc5, 0}, {0, 0}},

C[ S[4] , V[2] , V[2] ] == {{I*gc6, 0}, {0, 0}},

C[ S[4] , V[3] , -V[3] ] == {{I*gc7, 0}, {0, 0}},

C[ S[4] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*gc8*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -U[4, {e1x1}] , U[4, {e2x1}] , V[4, {e3x2}] ] == {{gc9*SUNF[e3x2, e1x1, e2x1], 0}, {gc9*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc10*SUNF[e1x2, e2x2, e3x2]), 0}, {gc10*SUNF[e1x2, e2x2, e3x2], 0}, {gc10*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc10*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc10*SUNF[e1x2, e2x2, e3x2]), 0}, {gc10*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc11*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc11*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc11*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[4] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{gc12*SUNF[e1x2, e2x2, e3x2], 0}, {gc12*SUNF[e1x2, e2x2, e3x2], 0}, {gc12*SUNF[e1x2, e2x2, e3x2], 0}},

C[ S[4] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(4*I)*CGa*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc14L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc14R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc15L[e1x2, e2x2], 0}, {I*gc15R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc16L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc16R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[4] ] == {{gc17L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc17R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[4] ] == {{gc18L[e1x2, e2x2], 0}, {gc18R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[4] ] == {{gc19L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc19R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc20, 0}, {I*gc20, 0}, {I*gc20, 0}, {(-I)*gc20, 0}, {(-I)*gc20, 0}, {I*gc20, 0}},

C[ S[4] , V[1] , V[3] , -V[3] ] == {{I*gc21, 0}, {I*gc21, 0}, {I*gc21, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc23, 0}, {(-I)*gc23, 0}, {(2*I)*gc23, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc24, 0}, {I*gc24, 0}, {I*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {I*gc24, 0}},

C[ S[4] , V[3] , -V[3] , V[2] ] == {{I*gc25, 0}, {I*gc25, 0}, {I*gc25, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc26, 0}, {(-I)*gc26, 0}, {(2*I)*gc26, 0}},

C[ S[1] , S[4] , V[2] ] == {{gc27, 0}, {0, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc28, 0}, {I*gc28, 0}, {I*gc28, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {I*gc30, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc31, 0}, {(-I)*gc31, 0}, {(2*I)*gc31, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc32*IndexDelta[e1x2, e2x2], 0}, {I*gc32*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc34*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc34*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc35*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc35*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc36*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc36*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc37[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc38[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc39*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc40*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc41L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc41R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc42L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc42R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc43*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc44L*IndexDelta[e1x2, e2x2], 0}, {I*gc44R*IndexDelta[e1x2, e2x2], 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc2 -> -6*lam*vev,
     gc3 -> -2*Chaa,
     gc4 -> 4*(CBa*cw^2 + CWa*sw^2),
     gc5 -> -4*cw*(CBa - CWa)*sw,
     gc6 -> 4*(cw^2*CWa + CBa*sw^2),
     gc7 -> 4*CWa,
     gc8 -> 4*CGa,
     gc9 -> GS,
     gc10 -> -GS,
     gc11 -> -GS^2,
     gc12 -> 4*CGa*GS,
     gc14L[e1x2_, e2x2_] -> -(Conjugate[yd[e2x2, e1x2]]/Sqrt[2]),
     gc14R[e1x2_, e2x2_] -> -(yd[e1x2, e2x2]/Sqrt[2]),
     gc15L[e1x2_, e2x2_] -> -(Conjugate[yl[e2x2, e1x2]]/Sqrt[2]),
     gc15R[e1x2_, e2x2_] -> -(yl[e1x2, e2x2]/Sqrt[2]),
     gc16L[e1x2_, e2x2_] -> -(Conjugate[yu[e2x2, e1x2]]/Sqrt[2]),
     gc16R[e1x2_, e2x2_] -> -(yu[e1x2, e2x2]/Sqrt[2]),
     gc17L[e1x2_, e2x2_] -> -((Cf*Gamma5*Conjugate[yd[e2x2, e1x2]])/fa),
     gc17R[e1x2_, e2x2_] -> (Cf*Gamma5*yd[e1x2, e2x2])/fa,
     gc18L[e1x2_, e2x2_] -> -((Cf*Gamma5*Conjugate[yl[e2x2, e1x2]])/fa),
     gc18R[e1x2_, e2x2_] -> (Cf*Gamma5*yl[e1x2, e2x2])/fa,
     gc19L[e1x2_, e2x2_] -> -((Cf*Gamma5*Conjugate[yu[e2x2, e1x2]])/fa),
     gc19R[e1x2_, e2x2_] -> (Cf*Gamma5*yu[e1x2, e2x2])/fa,
     gc20 -> EL,
     gc21 -> -4*CWa*EL,
     gc23 -> -EL^2,
     gc24 -> (cw*EL)/sw,
     gc25 -> (-4*cw*CWa*EL)/sw,
     gc26 -> EL^2/sw^2,
     gc27 -> ChZa,
     gc28 -> (cw*EL^2)/sw,
     gc30 -> (EL^2*(cw^2 + sw^2)^2*vev)/(2*cw^2*sw^2),
     gc31 -> -((cw^2*EL^2)/sw^2),
     gc32 -> -EL,
     gc33 -> (2*EL)/3,
     gc34 -> -EL/3,
     gc35 -> GS,
     gc36 -> GS,
     gc37[e1x2_, e2x2_] -> (EL*CKM[e1x2, e2x2])/(Sqrt[2]*sw),
     gc38[e1x2_, e2x2_] -> (EL*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*sw),
     gc39 -> EL/(Sqrt[2]*sw),
     gc40 -> EL/(Sqrt[2]*sw),
     gc41L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc41R -> (-2*EL*sw)/(3*cw),
     gc42L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc42R -> (EL*sw)/(3*cw),
     gc43 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc44L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc44R -> (EL*sw)/cw};

