! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 9/23/2019 , 15:54:12
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.4.0
! Model name: fr_chpseudo
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 500
! --------------------------------------------------------------------------------
! FeynRules model: CHpseudo
! FeynRules version: 2.3.32
! --------------------------------------------------------------------------------

module parameters_fr_chpseudo_local
use parameters_fr_chpseudo_global
implicit none
public
save

real(kind=default) :: fa, Cf, Kg, Kw, Kb, kV, kt, aEWM1, Gf, aS, ymdo, ymup, yms &
   , ymc, ymb, ymt, yme, ymm, ymtau, Kaa, taub, taut, aEW, G, ee, sw2, cw, sw, Kza,  &
   Kzz, g1, gw, vev, lam, yb, yc, ydo, ye, ym, ys, yt, ytau, yup, muH

end module parameters_fr_chpseudo_local