! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 9/23/2019 , 15:54:12
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.4.0
! Model name: fr_chpseudo
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 500
! --------------------------------------------------------------------------------
! FeynRules model: CHpseudo
! FeynRules version: 2.3.32
! --------------------------------------------------------------------------------

module parameters_fr_chpseudo_cpl1
use parameters_fr_chpseudo_global
use parameters_fr_chpseudo_local
implicit none

contains

subroutine calc_cpl1
   G_h_1_h_1_h_1_h_1 = -6*lam
   G_h_1_h_1_h_1 = -6*lam*vev
   G_g_1_g_1_g_1 = ((0,-1)*G)/Sqrt (2._default)
   G_g_1_g_1_g_1_g_1 = -G**2/2._default
   G_u_bar_psa_1_u(1) = ((0,0.5_default)*Cf*vev*yup)/(Sqrt (2._default)*fa)
   G_u_bar_psa_1_u(2) = ((0,-0.5_default)*Cf*vev*yup)/(Sqrt (2._default)*fa)
   G_c_bar_psa_1_c(1) = ((0,0.5_default)*Cf*vev*yc)/(Sqrt (2._default)*fa)
   G_c_bar_psa_1_c(2) = ((0,-0.5_default)*Cf*vev*yc)/(Sqrt (2._default)*fa)
   G_t_bar_psa_1_t(1) = ((0,0.5_default)*Cf*vev*yt)/(Sqrt (2._default)*fa)
   G_t_bar_psa_1_t(2) = ((0,-0.5_default)*Cf*vev*yt)/(Sqrt (2._default)*fa)
   G_u_bar_h_1_u(1) = -yup/(2._default*Sqrt (2._default))
   G_u_bar_h_1_u(2) = -yup/(2._default*Sqrt (2._default))
   G_c_bar_h_1_c(1) = -yc/(2._default*Sqrt (2._default))
   G_c_bar_h_1_c(2) = -yc/(2._default*Sqrt (2._default))
   G_t_bar_h_1_t(1) = -yt/(2._default*Sqrt (2._default))
   G_t_bar_h_1_t(2) = -yt/(2._default*Sqrt (2._default))
   G_d_bar_psa_1_d(1) = ((0,0.5_default)*Cf*vev*ydo)/(Sqrt (2._default)*fa)
   G_d_bar_psa_1_d(2) = ((0,-0.5_default)*Cf*vev*ydo)/(Sqrt (2._default)*fa)
   G_s_bar_psa_1_s(1) = ((0,0.5_default)*Cf*vev*ys)/(Sqrt (2._default)*fa)
   G_s_bar_psa_1_s(2) = ((0,-0.5_default)*Cf*vev*ys)/(Sqrt (2._default)*fa)
   G_b_bar_psa_1_b(1) = ((0,0.5_default)*Cf*vev*yb)/(Sqrt (2._default)*fa)
   G_b_bar_psa_1_b(2) = ((0,-0.5_default)*Cf*vev*yb)/(Sqrt (2._default)*fa)
   G_d_bar_h_1_d(1) = -ydo/(2._default*Sqrt (2._default))
   G_d_bar_h_1_d(2) = -ydo/(2._default*Sqrt (2._default))
   G_s_bar_h_1_s(1) = -ys/(2._default*Sqrt (2._default))
   G_s_bar_h_1_s(2) = -ys/(2._default*Sqrt (2._default))
   G_b_bar_h_1_b(1) = -yb/(2._default*Sqrt (2._default))
   G_b_bar_h_1_b(2) = -yb/(2._default*Sqrt (2._default))
   G_e_plus_psa_1_e_minus(1) = ((0,0.5_default)*Cf*vev*ye)/(Sqrt (2._default)*fa)
   G_e_plus_psa_1_e_minus(2) = ((0,-0.5_default)*Cf*vev*ye)/(Sqrt (2._default)*fa)
   G_mu_plus_psa_1_mu_minus(1) = ((0,0.5_default)*Cf*vev*ym)/(Sqrt (2._default)*fa)
   G_mu_plus_psa_1_mu_minus(2) = ((0,-0.5_default)*Cf*vev*ym)/(Sqrt (2._default)*fa &
      )
   G_ta_plus_psa_1_ta_minus(1) = ((0,0.5_default)*Cf*vev*ytau)/(Sqrt (2._default)* &
      fa)
   G_ta_plus_psa_1_ta_minus(2) = ((0,-0.5_default)*Cf*vev*ytau)/(Sqrt (2._default)* &
      fa)
   G_e_plus_h_1_e_minus(1) = -ye/(2._default*Sqrt (2._default))
   G_e_plus_h_1_e_minus(2) = -ye/(2._default*Sqrt (2._default))
   G_mu_plus_h_1_mu_minus(1) = -ym/(2._default*Sqrt (2._default))
   G_mu_plus_h_1_mu_minus(2) = -ym/(2._default*Sqrt (2._default))
   G_ta_plus_h_1_ta_minus(1) = -ytau/(2._default*Sqrt (2._default))
   G_ta_plus_h_1_ta_minus(2) = -ytau/(2._default*Sqrt (2._default))
   G_a_1_w_plus_w_minus = (0,1)*ee
   G_h_1_h_1_w_plus_w_minus = ee**2/(2._default*sw**2)
   G_h_1_w_plus_w_minus = (ee**2*vev)/(2._default*sw**2)
   G_a_1_a_1_w_plus_w_minus = -ee**2
   G_w_plus_w_minus_z_1 = ((0,1)*cw*ee)/sw
   G_w_plus_w_plus_w_minus_w_minus = ee**2/sw**2
   G_a_1_w_plus_w_minus_z_1 = (cw*ee**2)/sw
   G_h_1_h_1_z_1_z_1 = (ee**2*(cw**2 + sw**2)**2)/(2._default*cw**2*sw**2)
   G_h_1_z_1_z_1 = (ee**2*(cw**2 + sw**2)**2*vev)/(2._default*cw**2*sw**2)
   G_w_plus_w_minus_z_1_z_1 = -((cw**2*ee**2)/sw**2)
   G_e_plus_a_1_e_minus = -ee
   G_ve_bar_z_1_ve = (ee*(cw**2 + sw**2))/(4._default*cw*sw)
   G_e_plus_z_1_e_minus(1) = -(cw*ee)/(4._default*sw) + (ee*sw)/(4._default*cw)
   G_e_plus_z_1_e_minus(2) = (ee*sw)/(2._default*cw)
   G_u_bar_a_1_u = (2*ee)/3._default
   G_d_bar_a_1_d = -ee/3._default
   G_u_bar_z_1_u(1) = (cw*ee)/(4._default*sw) - (ee*sw)/(12._default*cw)
   G_u_bar_z_1_u(2) = -(ee*sw)/(3._default*cw)
   G_d_bar_z_1_d(1) = -(ee*(3*cw**2 + sw**2))/(12._default*cw*sw)
   G_d_bar_z_1_d(2) = (ee*sw)/(6._default*cw)
   G_u_bar_g_1_u = G/Sqrt (2._default)
   G_u_bar_w_plus_d = ee/(2._default*Sqrt (2._default)*sw)
end subroutine calc_cpl1

end module parameters_fr_chpseudo_cpl1