! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 9/23/2019 , 15:54:12
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.4.0
! Model name: fr_chpseudo
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 500
! --------------------------------------------------------------------------------
! FeynRules model: CHpseudo
! FeynRules version: 2.3.32
! --------------------------------------------------------------------------------

module parameters_fr_chpseudo
use parameters_fr_chpseudo_global
implicit none
public
private :: sec, csc
save

contains

subroutine import_from_whizard (par, scheme)
use parameters_fr_chpseudo_local
use parameters_fr_chpseudo_cpl1
real(kind=default), dimension(63), intent(in) :: par
integer, intent(in) :: scheme
   fa = par(1)
   Cf = par(2)
   Kg = par(3)
   Kw = par(4)
   Kb = par(5)
   kV = par(6)
   kt = par(7)
   aEWM1 = par(8)
   Gf = par(9)
   aS = par(10)
   ymdo = par(11)
   ymup = par(12)
   yms = par(13)
   ymc = par(14)
   ymb = par(15)
   ymt = par(16)
   yme = par(17)
   ymm = par(18)
   ymtau = par(19)
   Me = par(20)
   MMU = par(21)
   MTA = par(22)
   MU = par(23)
   MC = par(24)
   MT = par(25)
   MD = par(26)
   MS = par(27)
   MB = par(28)
   MH = par(29)
   MZ = par(30)
   Mpsa = par(31)
   WT = par(32)
   WH = par(33)
   WZ = par(34)
   WW = par(35)
   Wpsa = par(36)
   Kaa = par(37)
   taub = par(38)
   taut = par(39)
   aEW = par(40)
   G = par(41)
   MW = par(42)
   ee = par(43)
   sw2 = par(44)
   cw = par(45)
   sw = par(46)
   Kza = par(47)
   Kzz = par(48)
   g1 = par(49)
   gw = par(50)
   vev = par(51)
   lam = par(52)
   yb = par(53)
   yc = par(54)
   ydo = par(55)
   ye = par(56)
   ym = par(57)
   ys = par(58)
   yt = par(59)
   ytau = par(60)
   yup = par(61)
   muH = par(62)
   call calc_cpl1
end subroutine import_from_whizard

subroutine model_update_alpha_s (alpha_s)
use parameters_fr_chpseudo_local
real(kind=default), intent(in) :: alpha_s
   aS = alpha_s
   G = 2*sqrt(aS)*sqrt(3.141592653589793_default)
   G_g_1_g_1_g_1 = ((0,-1)*G)/Sqrt (2._default)
   G_g_1_g_1_g_1_g_1 = -G**2/2._default
   G_u_bar_g_1_u = G/Sqrt (2._default)
end subroutine model_update_alpha_s

end module parameters_fr_chpseudo