! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 9/23/2019 , 15:54:12
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.4.0
! Model name: fr_chpseudo
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 500
! --------------------------------------------------------------------------------
! FeynRules model: CHpseudo
! FeynRules version: 2.3.32
! --------------------------------------------------------------------------------

module parameters_fr_chpseudo_global
use kinds
use constants, only: pi
implicit none
public
private :: sec_re, sec_cmplx, csc_re, csc_cmplx
save

real(kind=default), parameter :: fr_zero=0.
! masses and widths:
real(kind=default) :: Me, MMU, MTA, MU, MC, MT, MD, MS, MB, MH, MZ, MW, Mpsa, WT &
   , WH, WZ, WW, Wpsa
! vertex factors:
complex(kind=default) :: G_h_1_h_1_h_1_h_1, G_h_1_h_1_h_1, G_g_1_g_1_g_1,  &
   G_g_1_g_1_g_1_g_1, G_u_bar_psa_1_u(2), G_c_bar_psa_1_c(2), G_t_bar_psa_1_t(2), G_u_bar_h_1_u(2),  &
   G_c_bar_h_1_c(2), G_t_bar_h_1_t(2), G_d_bar_psa_1_d(2), G_s_bar_psa_1_s(2), G_b_bar_psa_1_b(2 &
   ), G_d_bar_h_1_d(2), G_s_bar_h_1_s(2), G_b_bar_h_1_b(2), G_e_plus_psa_1_e_minus(2 &
   ), G_mu_plus_psa_1_mu_minus(2), G_ta_plus_psa_1_ta_minus(2), G_e_plus_h_1_e_minus(2 &
   ), G_mu_plus_h_1_mu_minus(2), G_ta_plus_h_1_ta_minus(2), G_a_1_w_plus_w_minus,  &
   G_h_1_h_1_w_plus_w_minus, G_h_1_w_plus_w_minus, G_a_1_a_1_w_plus_w_minus, G_w_plus_w_minus_z_1,  &
   G_w_plus_w_plus_w_minus_w_minus, G_a_1_w_plus_w_minus_z_1, G_h_1_h_1_z_1_z_1, G_h_1_z_1_z_1,  &
   G_w_plus_w_minus_z_1_z_1, G_e_plus_a_1_e_minus, G_ve_bar_z_1_ve, G_e_plus_z_1_e_minus(2), G_u_bar_a_1_u &
   , G_d_bar_a_1_d, G_u_bar_z_1_u(2), G_d_bar_z_1_d(2), G_u_bar_g_1_u,  &
   G_u_bar_w_plus_d

interface sec
   module procedure sec_re
   module procedure sec_cmplx
end interface sec

interface csc
   module procedure csc_re
   module procedure csc_cmplx
end interface csc

contains

function sec_re (x) result (y)
real(kind=default), intent(in) :: x
real(kind=default) :: y
   y = 1._default / cos (x)
end function sec_re

function sec_cmplx (x) result (y)
complex(kind=default), intent(in) :: x
complex(kind=default) :: y
   y = 1._default / cos (x)
end function sec_cmplx

function csc_re (x) result (y)
real(kind=default), intent(in) :: x
real(kind=default) :: y
   y = 1._default / cos (x)
end function csc_re

function csc_cmplx (x) result (y)
complex(kind=default), intent(in) :: x
complex(kind=default) :: y
   y = 1._default / cos (x)
end function csc_cmplx

end module parameters_fr_chpseudo_global