binaries = \
   omega_fr_chpseudo.opt

int_fr_chpseudo = fr_chpseudo_mdl.cmi

mdl_fr_chpseudo = fr_chpseudo_mdl.cmx

bin_fr_chpseudo = omega_fr_chpseudo.cmx


$(mdl_fr_chpseudo): $(int_fr_chpseudo)
$(bin_fr_chpseudo): $(int_fr_chpseudo) $(mdl_fr_chpseudo)
omega_fr_chpseudo.opt: $(int_fr_chpseudo) $(mdl_fr_chpseudo) $(bin_fr_chpseudo)
	$(ocamlopt) $(ocamlflags) -I $(libdir) -o $@ unix.cmxa omega_core.cmxa omega_targets.cmxa \
	   $(mdl_fr_chpseudo) $(bin_fr_chpseudo)
