(* --------------------------------------------------------------------------------
   Autogenerated by the happy scrappy WHIZARD model file generator on 9/23/2019 , 15:54:12
   WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
   Code generated for WHIZARD / O'Mega version 2.4.0
   Model name: fr_chpseudo
   Gauge: Unitarity
   Maximum number of couplings per FORTRAN module: 500
   --------------------------------------------------------------------------------
   FeynRules model: CHpseudo
   FeynRules version: 2.3.32
   -------------------------------------------------------------------------------- *)

module O =  Omega.Make (Fusion.Mixed23) (Targets.Fortran)
   (Fr_chpseudo_mdl.Implementation (struct let gauge = Fr_chpseudo_mdl.Unitarity let color = true end))

let _ = O.main ()
