(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"CHpseudo",
  Authors -> {"L. Mason", "B. Fuks"},
  Version -> "1.1",
  Date -> "03.05.2019",
  Institutions -> {"University of Johannesburg/University of Lyon", "LPTHE / Sorbonne U."},
  Emails -> {"lara.mason@live.com", "fuks@lpthe.jussieu.fr"},
  URLs -> ""};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3], psa -> S[4]};

FR$InteractionOrderPerturbativeExpansion={{NP, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mpsa,
    Indices -> {},
    PropagatorLabel -> "psa" }
}


(*        Definitions       *)

GaugeXi[ U[3] ] = GaugeXi[U[31]];
GaugeXi[ U[4] ] = GaugeXi[U[32]];
GaugeXi[ U[5] ] = GaugeXi[U[4]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MH[ ___ ] := MH;
Mpsa[ ___ ] := Mpsa;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc11, 0}, {I*gc11, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc12, 0}, {I*gc12, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc13, 0}, {I*gc13, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc15, 0}, {I*gc15, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc18, 0}, {I*gc18, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc19, 0}, {I*gc19, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc21, 0}, {I*gc21, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc23, 0}, {I*gc23, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc26, 0}, {I*gc26, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc27, 0}, {I*gc27, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc29, 0}, {I*gc29, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc31, 0}, {I*gc31, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc33, 0}, {I*gc33, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/4)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc35*SUNF[e3x2, e1x1, e2x1], 0}, {gc35*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc36*SUNF[e1x2, e2x2, e3x2]), 0}, {gc36*SUNF[e1x2, e2x2, e3x2], 0}, {gc36*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc36*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc36*SUNF[e1x2, e2x2, e3x2]), 0}, {gc36*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc37*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc37*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc37*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc38L*IndexDelta[e1x2, e2x2], 0}, {gc38R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc39L*IndexDelta[e1x2, e2x2], 0}, {gc39R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc40L*IndexDelta[e1x2, e2x2], 0}, {gc40R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc41L*IndexDelta[e1x2, e2x2], 0}, {gc41R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc42*IndexDelta[e1x2, e2x2], 0}, {I*gc42*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc43L*IndexDelta[e1x2, e2x2], 0}, {gc43R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc44*IndexDelta[e1x2, e2x2], 0}, {I*gc44*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc45L*IndexDelta[e1x2, e2x2], 0}, {gc45R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc46*IndexDelta[e1x2, e2x2], 0}, {I*gc46*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc47L*IndexDelta[e1x2, e2x2], 0}, {gc47R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc48L*IndexDelta[e1x2, e2x2], 0}, {gc48R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc49*IndexDelta[e1x2, e2x2], 0}, {I*gc49*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc50L*IndexDelta[e1x2, e2x2], 0}, {gc50R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc51L*IndexDelta[e1x2, e2x2], 0}, {gc51R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc52*IndexDelta[e1x2, e2x2], 0}, {I*gc52*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc53L*IndexDelta[e1x2, e2x2], 0}, {gc53R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc54L*IndexDelta[e1x2, e2x2], 0}, {gc54R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc55*IndexDelta[e1x2, e2x2], 0}, {I*gc55*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[1] , -S[3] ] == {{gc56, 0}, {0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc57L, 0}, {gc57R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc58, 0}, {I*gc58, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc59, 0}, {0, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc60L, 0}, {gc60R, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc61, 0}, {I*gc61, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc62, 0}, {0, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc63L, 0}, {gc63R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc64, 0}, {I*gc64, 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc68, 0}, {I*gc68, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc69, 0}, {gc69, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc70, 0}, {I*gc70, 0}, {I*gc70, 0}, {(-I)*gc70, 0}, {(-I)*gc70, 0}, {I*gc70, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc74, 0}, {I*gc74, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc75, 0}, {gc75, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc80, 0}, {(-I)*gc80, 0}, {(2*I)*gc80, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc81, 0}, {I*gc81, 0}, {I*gc81, 0}, {(-I)*gc81, 0}, {(-I)*gc81, 0}, {I*gc81, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc82, 0}, {(-I)*gc82, 0}, {(2*I)*gc82, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {gc83R, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {gc84R, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc85R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc87, 0}, {gc87, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc88, 0}, {I*gc88, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*vev)/(2*cw), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc95, 0}, {I*gc95, 0}, {I*gc95, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc100, 0}, {(-I)*gc100, 0}, {(2*I)*gc100, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc101, 0}, {I*gc101, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc102, 0}, {I*gc102, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc103, 0}, {I*gc103, 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc104, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc105, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc106, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc107L, 0}, {I*gc107R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc108L, 0}, {I*gc108R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc109L, 0}, {I*gc109R, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc110*IndexDelta[e1x2, e2x2], 0}, {I*gc110*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc111*IndexDelta[e1x2, e2x2], 0}, {I*gc111*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc112*IndexDelta[e1x2, e2x2], 0}, {I*gc112*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc113*IndexDelta[e1x2, e2x2], 0}, {I*gc113*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc114*IndexDelta[e1x2, e2x2], 0}, {I*gc114*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc115*IndexDelta[e1x2, e2x2], 0}, {I*gc115*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc116L*IndexDelta[e1x2, e2x2], 0}, {I*gc116R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc117L*IndexDelta[e1x2, e2x2], 0}, {I*gc117R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc118L*IndexDelta[e1x2, e2x2], 0}, {I*gc118R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc119L*IndexDelta[e1x2, e2x2], 0}, {I*gc119R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc120L*IndexDelta[e1x2, e2x2], 0}, {I*gc120R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc121L*IndexDelta[e1x2, e2x2], 0}, {I*gc121R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc122*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc122*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc123*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc123*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc124*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc124*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc125*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc125*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc126*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc126*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc127*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc127*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc128*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc129*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc130*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc131*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc132*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc133*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc134, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc135, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc136, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc137, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc138, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc139, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc11 -> -EL,
     gc12 -> EL,
     gc13 -> -EL,
     gc15 -> EL,
     gc18 -> -EL,
     gc19 -> -((cw*EL)/sw),
     gc21 -> (cw*EL)/sw,
     gc23 -> -EL,
     gc26 -> EL,
     gc27 -> (cw*EL)/sw,
     gc29 -> -((cw*EL)/sw),
     gc31 -> (cw*EL)/sw,
     gc33 -> -((cw*EL)/sw),
     gc35 -> GS,
     gc36 -> -GS,
     gc37 -> -GS^2,
     gc38L -> yc,
     gc38R -> -ys,
     gc39L -> yt,
     gc39R -> -yb,
     gc40L -> yup,
     gc40R -> -ydo,
     gc41L -> yc/Sqrt[2],
     gc41R -> -(yc/Sqrt[2]),
     gc42 -> -(yc/Sqrt[2]),
     gc43L -> yt/Sqrt[2],
     gc43R -> -(yt/Sqrt[2]),
     gc44 -> -(yt/Sqrt[2]),
     gc45L -> yup/Sqrt[2],
     gc45R -> -(yup/Sqrt[2]),
     gc46 -> -(yup/Sqrt[2]),
     gc47L -> ydo,
     gc47R -> -yup,
     gc48L -> -(ydo/Sqrt[2]),
     gc48R -> ydo/Sqrt[2],
     gc49 -> -(ydo/Sqrt[2]),
     gc50L -> ys,
     gc50R -> -yc,
     gc51L -> -(ys/Sqrt[2]),
     gc51R -> ys/Sqrt[2],
     gc52 -> -(ys/Sqrt[2]),
     gc53L -> yb,
     gc53R -> -yt,
     gc54L -> -(yb/Sqrt[2]),
     gc54R -> yb/Sqrt[2],
     gc55 -> -(yb/Sqrt[2]),
     gc56 -> ye,
     gc57L -> -(ye/Sqrt[2]),
     gc57R -> ye/Sqrt[2],
     gc58 -> -(ye/Sqrt[2]),
     gc59 -> ym,
     gc60L -> -(ym/Sqrt[2]),
     gc60R -> ym/Sqrt[2],
     gc61 -> -(ym/Sqrt[2]),
     gc62 -> ytau,
     gc63L -> -(ytau/Sqrt[2]),
     gc63R -> ytau/Sqrt[2],
     gc64 -> -(ytau/Sqrt[2]),
     gc68 -> EL/(2*sw),
     gc69 -> -EL/(2*sw),
     gc70 -> EL,
     gc74 -> -EL/(2*sw),
     gc75 -> -EL/(2*sw),
     gc80 -> -EL^2,
     gc81 -> (cw*EL)/sw,
     gc82 -> EL^2/sw^2,
     gc83R -> -ye,
     gc84R -> -ym,
     gc85R -> -ytau,
     gc87 -> -(EL*(cw^2 + sw^2))/(2*cw*sw),
     gc88 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc95 -> (cw*EL^2)/sw,
     gc100 -> -((cw^2*EL^2)/sw^2),
     gc101 -> -EL,
     gc102 -> -EL,
     gc103 -> -EL,
     gc104 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc105 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc106 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc107L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc107R -> (EL*sw)/cw,
     gc108L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc108R -> (EL*sw)/cw,
     gc109L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc109R -> (EL*sw)/cw,
     gc110 -> (2*EL)/3,
     gc111 -> (2*EL)/3,
     gc112 -> (2*EL)/3,
     gc113 -> -EL/3,
     gc114 -> -EL/3,
     gc115 -> -EL/3,
     gc116L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc116R -> (-2*EL*sw)/(3*cw),
     gc117L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc117R -> (-2*EL*sw)/(3*cw),
     gc118L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc118R -> (-2*EL*sw)/(3*cw),
     gc119L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc119R -> (EL*sw)/(3*cw),
     gc120L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc120R -> (EL*sw)/(3*cw),
     gc121L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc121R -> (EL*sw)/(3*cw),
     gc122 -> GS,
     gc123 -> GS,
     gc124 -> GS,
     gc125 -> GS,
     gc126 -> GS,
     gc127 -> GS,
     gc128 -> EL/(Sqrt[2]*sw),
     gc129 -> EL/(Sqrt[2]*sw),
     gc130 -> EL/(Sqrt[2]*sw),
     gc131 -> EL/(Sqrt[2]*sw),
     gc132 -> EL/(Sqrt[2]*sw),
     gc133 -> EL/(Sqrt[2]*sw),
     gc134 -> EL/(Sqrt[2]*sw),
     gc135 -> EL/(Sqrt[2]*sw),
     gc136 -> EL/(Sqrt[2]*sw),
     gc137 -> EL/(Sqrt[2]*sw),
     gc138 -> EL/(Sqrt[2]*sw),
     gc139 -> EL/(Sqrt[2]*sw)};

