(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"CHpseudo",
  Authors -> {"L. Mason", "B. Fuks"},
  Version -> "1.1",
  Date -> "03.05.2019",
  Institutions -> {"University of Johannesburg/University of Lyon", "LPTHE / Sorbonne U."},
  Emails -> {"lara.mason@live.com", "fuks@lpthe.jussieu.fr"},
  URLs -> ""};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3], eta -> S[4]};

FR$InteractionOrderPerturbativeExpansion={{NP, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Meta,
    Indices -> {},
    PropagatorLabel -> "eta" }
}


(*        Definitions       *)

GaugeXi[ U[3] ] = GaugeXi[U[31]];
GaugeXi[ U[4] ] = GaugeXi[U[32]];
GaugeXi[ U[5] ] = GaugeXi[U[4]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MH[ ___ ] := MH;
Meta[ ___ ] := Meta;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[1] ] == {{I*gc7, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] ] == {{I*gc8, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] ] == {{I*gc9, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc11, 0}, {I*gc11, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc12, 0}, {I*gc12, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc13, 0}, {I*gc13, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc15, 0}, {I*gc15, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc18, 0}, {I*gc18, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc19, 0}, {I*gc19, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc21, 0}, {I*gc21, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc23, 0}, {I*gc23, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc26, 0}, {I*gc26, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc27, 0}, {I*gc27, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc29, 0}, {I*gc29, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc31, 0}, {I*gc31, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc33, 0}, {I*gc33, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/4)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[4] , V[1] , V[1] ] == {{I*gc35, 0}, {0, 0}},

C[ S[4] , V[3] , -V[3] ] == {{I*gc36, 0}, {0, 0}},

C[ S[4] , V[1] , V[2] ] == {{I*gc37, 0}, {0, 0}},

C[ S[4] , V[2] , V[2] ] == {{I*gc38, 0}, {0, 0}},

C[ S[4] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{I*gc39*IndexDelta[e2x2, e3x2], 0}, {0, 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc40*SUNF[e3x2, e1x1, e2x1], 0}, {gc40*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc41*SUNF[e1x2, e2x2, e3x2]), 0}, {gc41*SUNF[e1x2, e2x2, e3x2], 0}, {gc41*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc41*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc41*SUNF[e1x2, e2x2, e3x2]), 0}, {gc41*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc42*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc42*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc42*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[4] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{gc43*SUNF[e2x2, e3x2, e4x2], 0}, {gc43*SUNF[e2x2, e3x2, e4x2], 0}, {gc43*SUNF[e2x2, e3x2, e4x2], 0}},

C[ S[4] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] , V[4, {e5x2}] ] == {{((I/4)*GS^4*Kg*(SUNF[e2x2, e3x2, e4x2, e5x2] - SUNF[e2x2, e4x2, e3x2, e5x2] + SUNF[e2x2, e5x2, e3x2, e4x2]))/(fa*Pi^2), 0}},

C[ S[4] , S[4] , S[1] ] == {{0, 0}, {I*gc45, 0}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc46L*IndexDelta[e1x2, e2x2], 0}, {gc46R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc47L*IndexDelta[e1x2, e2x2], 0}, {gc47R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc48L*IndexDelta[e1x2, e2x2], 0}, {gc48R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc49L*IndexDelta[e1x2, e2x2], 0}, {gc49R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc50*IndexDelta[e1x2, e2x2], 0}, {I*gc50*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc51L*IndexDelta[e1x2, e2x2], 0}, {gc51R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc52*IndexDelta[e1x2, e2x2], 0}, {I*gc52*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc53L*IndexDelta[e1x2, e2x2], 0}, {gc53R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc54*IndexDelta[e1x2, e2x2], 0}, {I*gc54*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[4] , S[3] ] == {{I*gc55*yc*IndexDelta[e1x2, e2x2], 0}, {I*gc55*ys*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[4] , S[3] ] == {{I*gc56*yt*IndexDelta[e1x2, e2x2], 0}, {I*gc56*yb*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[4] , S[3] ] == {{I*gc57*yup*IndexDelta[e1x2, e2x2], 0}, {I*gc57*ydo*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[4] , S[2] ] == {{I*gc58*IndexDelta[e1x2, e2x2], 0}, {I*gc58*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[4] , S[1] ] == {{-(gc59*IndexDelta[e1x2, e2x2]), 0}, {gc59*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[4] ] == {{gc60L*IndexDelta[e1x2, e2x2], 0}, {gc60R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[4] , S[2] ] == {{I*gc61*IndexDelta[e1x2, e2x2], 0}, {I*gc61*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[4] , S[1] ] == {{-(gc62*IndexDelta[e1x2, e2x2]), 0}, {gc62*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[4] ] == {{gc63L*IndexDelta[e1x2, e2x2], 0}, {gc63R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[4] , S[2] ] == {{I*gc64*IndexDelta[e1x2, e2x2], 0}, {I*gc64*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[4] , S[1] ] == {{-(gc65*IndexDelta[e1x2, e2x2]), 0}, {gc65*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[4] ] == {{gc66L*IndexDelta[e1x2, e2x2], 0}, {gc66R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc67L*IndexDelta[e1x2, e2x2], 0}, {gc67R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc68L*IndexDelta[e1x2, e2x2], 0}, {gc68R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc69*IndexDelta[e1x2, e2x2], 0}, {I*gc69*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc70L*IndexDelta[e1x2, e2x2], 0}, {gc70R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc71L*IndexDelta[e1x2, e2x2], 0}, {gc71R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc72*IndexDelta[e1x2, e2x2], 0}, {I*gc72*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc73L*IndexDelta[e1x2, e2x2], 0}, {gc73R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc74L*IndexDelta[e1x2, e2x2], 0}, {gc74R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc75*IndexDelta[e1x2, e2x2], 0}, {I*gc75*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , S[4] , -S[3] ] == {{I*gc76*ydo*IndexDelta[e1x2, e2x2], 0}, {I*gc76*yup*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[4] , S[2] ] == {{I*gc77*IndexDelta[e1x2, e2x2], 0}, {I*gc77*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[4] , S[1] ] == {{-(gc78*IndexDelta[e1x2, e2x2]), 0}, {gc78*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[4] ] == {{gc79L*IndexDelta[e1x2, e2x2], 0}, {gc79R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , S[4] , -S[3] ] == {{I*gc80*ys*IndexDelta[e1x2, e2x2], 0}, {I*gc80*yc*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[4] , S[2] ] == {{I*gc81*IndexDelta[e1x2, e2x2], 0}, {I*gc81*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[4] , S[1] ] == {{-(gc82*IndexDelta[e1x2, e2x2]), 0}, {gc82*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[4] ] == {{gc83L*IndexDelta[e1x2, e2x2], 0}, {gc83R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , S[4] , -S[3] ] == {{I*gc84*yb*IndexDelta[e1x2, e2x2], 0}, {I*gc84*yt*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[4] , S[2] ] == {{I*gc85*IndexDelta[e1x2, e2x2], 0}, {I*gc85*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[4] , S[1] ] == {{-(gc86*IndexDelta[e1x2, e2x2]), 0}, {gc86*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[4] ] == {{gc87L*IndexDelta[e1x2, e2x2], 0}, {gc87R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[1] , -S[3] ] == {{gc88, 0}, {0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc89L, 0}, {gc89R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc90, 0}, {I*gc90, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc91, 0}, {0, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc92L, 0}, {gc92R, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc93, 0}, {I*gc93, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc94, 0}, {0, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc95L, 0}, {gc95R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc96, 0}, {I*gc96, 0}},

C[ -F[4] , F[1] , S[4] , -S[3] ] == {{I*gc97, 0}, {0, 0}},

C[ -F[4] , F[4] , S[4] , S[2] ] == {{I*gc98, 0}, {I*gc98, 0}},

C[ -F[4] , F[4] , S[4] , S[1] ] == {{-gc99, 0}, {gc99, 0}},

C[ -F[4] , F[4] , S[4] ] == {{gc100L, 0}, {gc100R, 0}},

C[ -F[5] , F[2] , S[4] , -S[3] ] == {{I*gc101, 0}, {0, 0}},

C[ -F[5] , F[5] , S[4] , S[2] ] == {{I*gc102, 0}, {I*gc102, 0}},

C[ -F[5] , F[5] , S[4] , S[1] ] == {{-gc103, 0}, {gc103, 0}},

C[ -F[5] , F[5] , S[4] ] == {{gc104L, 0}, {gc104R, 0}},

C[ -F[6] , F[3] , S[4] , -S[3] ] == {{I*gc105, 0}, {0, 0}},

C[ -F[6] , F[6] , S[4] , S[2] ] == {{I*gc106, 0}, {I*gc106, 0}},

C[ -F[6] , F[6] , S[4] , S[1] ] == {{-gc107, 0}, {gc107, 0}},

C[ -F[6] , F[6] , S[4] ] == {{gc108L, 0}, {gc108R, 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc111, 0}, {I*gc111, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc112, 0}, {gc112, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc113, 0}, {I*gc113, 0}, {I*gc113, 0}, {(-I)*gc113, 0}, {(-I)*gc113, 0}, {I*gc113, 0}},

C[ S[4] , V[1] , V[3] , -V[3] ] == {{I*gc114, 0}, {I*gc114, 0}, {I*gc114, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc117, 0}, {I*gc117, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc118, 0}, {gc118, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc122, 0}, {(-I)*gc122, 0}, {(2*I)*gc122, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc123, 0}, {I*gc123, 0}, {I*gc123, 0}, {(-I)*gc123, 0}, {(-I)*gc123, 0}, {I*gc123, 0}},

C[ S[4] , V[3] , -V[3] , V[2] ] == {{I*gc124, 0}, {I*gc124, 0}, {I*gc124, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc125, 0}, {(-I)*gc125, 0}, {(2*I)*gc125, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {gc126R, 0}},

C[ -F[1] , F[4] , S[4] , S[3] ] == {{0, 0}, {I*gc127, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {gc128R, 0}},

C[ -F[2] , F[5] , S[4] , S[3] ] == {{0, 0}, {I*gc129, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc130R, 0}},

C[ -F[3] , F[6] , S[4] , S[3] ] == {{0, 0}, {I*gc131, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc133, 0}, {gc133, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc134, 0}, {I*gc134, 0}},

C[ S[4] , S[1] , V[2] ] == {{gc135, 0}, {0, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc140, 0}, {I*gc140, 0}, {I*gc140, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {I*gc144, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc145, 0}, {(-I)*gc145, 0}, {(2*I)*gc145, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc146, 0}, {I*gc146, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc147, 0}, {I*gc147, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc148, 0}, {I*gc148, 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc149, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc150, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc151, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc152L, 0}, {I*gc152R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc153L, 0}, {I*gc153R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc154L, 0}, {I*gc154R, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc155*IndexDelta[e1x2, e2x2], 0}, {I*gc155*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc156*IndexDelta[e1x2, e2x2], 0}, {I*gc156*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc157*IndexDelta[e1x2, e2x2], 0}, {I*gc157*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc158*IndexDelta[e1x2, e2x2], 0}, {I*gc158*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc159*IndexDelta[e1x2, e2x2], 0}, {I*gc159*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc160*IndexDelta[e1x2, e2x2], 0}, {I*gc160*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc161L*IndexDelta[e1x2, e2x2], 0}, {I*gc161R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc162L*IndexDelta[e1x2, e2x2], 0}, {I*gc162R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc163L*IndexDelta[e1x2, e2x2], 0}, {I*gc163R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc164L*IndexDelta[e1x2, e2x2], 0}, {I*gc164R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc165L*IndexDelta[e1x2, e2x2], 0}, {I*gc165R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc166L*IndexDelta[e1x2, e2x2], 0}, {I*gc166R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc167*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc167*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc168*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc168*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc169*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc169*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc170*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc170*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc171*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc171*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc172*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc172*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc173*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc174*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc175*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc176*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc177*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc178*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc179, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc180, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc181, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc182, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc183, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc184, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc7 -> -2*lam*vev,
     gc8 -> -2*lam*vev,
     gc9 -> -6*lam*vev,
     gc11 -> -EL,
     gc12 -> EL,
     gc13 -> -EL,
     gc15 -> EL,
     gc18 -> -EL,
     gc19 -> -((cw*EL)/sw),
     gc21 -> (cw*EL)/sw,
     gc23 -> -EL,
     gc26 -> EL,
     gc27 -> (cw*EL)/sw,
     gc29 -> -((cw*EL)/sw),
     gc31 -> (cw*EL)/sw,
     gc33 -> -((cw*EL)/sw),
     gc35 -> (EL^2*(Kb + Kw))/(4*fa*Pi^2),
     gc36 -> (EL^2*Kw)/(4*fa*Pi^2*sw^2),
     gc37 -> (EL^2*(cw^2*Kw - Kb*sw^2))/(4*cw*fa*Pi^2*sw),
     gc38 -> (EL^2*(cw^4*Kw + Kb*sw^4))/(4*cw^2*fa*Pi^2*sw^2),
     gc39 -> (GS^2*Kg)/(4*fa*Pi^2),
     gc40 -> GS,
     gc41 -> -GS,
     gc42 -> -GS^2,
     gc43 -> (GS^3*Kg)/(4*fa*Pi^2),
     gc45 -> (-3*Ct^2*kt*MT^2*Log[(16*fa^2*Pi^2)/MT^2])/(4*fa^2*Pi^2*vev),
     gc46L -> yc,
     gc46R -> -ys,
     gc47L -> yt,
     gc47R -> -yb,
     gc48L -> yup,
     gc48R -> -ydo,
     gc49L -> yc/Sqrt[2],
     gc49R -> -(yc/Sqrt[2]),
     gc50 -> -(yc/Sqrt[2]),
     gc51L -> yt/Sqrt[2],
     gc51R -> -(yt/Sqrt[2]),
     gc52 -> -(yt/Sqrt[2]),
     gc53L -> yup/Sqrt[2],
     gc53R -> -(yup/Sqrt[2]),
     gc54 -> -(yup/Sqrt[2]),
     gc55 -> -(Cf/(Sqrt[2]*fa)),
     gc56 -> -(Cf/(Sqrt[2]*fa)),
     gc57 -> -(Cf/(Sqrt[2]*fa)),
     gc58 -> -(Cf*yc)/(2*fa),
     gc59 -> (Cf*yc)/(2*fa),
     gc60L -> -(Cf*vev*yc)/(2*fa),
     gc60R -> (Cf*vev*yc)/(2*fa),
     gc61 -> -(Cf*yt)/(2*fa),
     gc62 -> (Cf*yt)/(2*fa),
     gc63L -> -(Cf*vev*yt)/(2*fa),
     gc63R -> (Cf*vev*yt)/(2*fa),
     gc64 -> -(Cf*yup)/(2*fa),
     gc65 -> (Cf*yup)/(2*fa),
     gc66L -> -(Cf*vev*yup)/(2*fa),
     gc66R -> (Cf*vev*yup)/(2*fa),
     gc67L -> ydo,
     gc67R -> -yup,
     gc68L -> -(ydo/Sqrt[2]),
     gc68R -> ydo/Sqrt[2],
     gc69 -> -(ydo/Sqrt[2]),
     gc70L -> ys,
     gc70R -> -yc,
     gc71L -> -(ys/Sqrt[2]),
     gc71R -> ys/Sqrt[2],
     gc72 -> -(ys/Sqrt[2]),
     gc73L -> yb,
     gc73R -> -yt,
     gc74L -> -(yb/Sqrt[2]),
     gc74R -> yb/Sqrt[2],
     gc75 -> -(yb/Sqrt[2]),
     gc76 -> -(Cf/(Sqrt[2]*fa)),
     gc77 -> (Cf*ydo)/(2*fa),
     gc78 -> (Cf*ydo)/(2*fa),
     gc79L -> -(Cf*vev*ydo)/(2*fa),
     gc79R -> (Cf*vev*ydo)/(2*fa),
     gc80 -> -(Cf/(Sqrt[2]*fa)),
     gc81 -> (Cf*ys)/(2*fa),
     gc82 -> (Cf*ys)/(2*fa),
     gc83L -> -(Cf*vev*ys)/(2*fa),
     gc83R -> (Cf*vev*ys)/(2*fa),
     gc84 -> -(Cf/(Sqrt[2]*fa)),
     gc85 -> (Cf*yb)/(2*fa),
     gc86 -> (Cf*yb)/(2*fa),
     gc87L -> -(Cf*vev*yb)/(2*fa),
     gc87R -> (Cf*vev*yb)/(2*fa),
     gc88 -> ye,
     gc89L -> -(ye/Sqrt[2]),
     gc89R -> ye/Sqrt[2],
     gc90 -> -(ye/Sqrt[2]),
     gc91 -> ym,
     gc92L -> -(ym/Sqrt[2]),
     gc92R -> ym/Sqrt[2],
     gc93 -> -(ym/Sqrt[2]),
     gc94 -> ytau,
     gc95L -> -(ytau/Sqrt[2]),
     gc95R -> ytau/Sqrt[2],
     gc96 -> -(ytau/Sqrt[2]),
     gc97 -> -((Cf*ye)/(Sqrt[2]*fa)),
     gc98 -> (Cf*ye)/(2*fa),
     gc99 -> (Cf*ye)/(2*fa),
     gc100L -> -(Cf*vev*ye)/(2*fa),
     gc100R -> (Cf*vev*ye)/(2*fa),
     gc101 -> -((Cf*ym)/(Sqrt[2]*fa)),
     gc102 -> (Cf*ym)/(2*fa),
     gc103 -> (Cf*ym)/(2*fa),
     gc104L -> -(Cf*vev*ym)/(2*fa),
     gc104R -> (Cf*vev*ym)/(2*fa),
     gc105 -> -((Cf*ytau)/(Sqrt[2]*fa)),
     gc106 -> (Cf*ytau)/(2*fa),
     gc107 -> (Cf*ytau)/(2*fa),
     gc108L -> -(Cf*vev*ytau)/(2*fa),
     gc108R -> (Cf*vev*ytau)/(2*fa),
     gc111 -> EL/(2*sw),
     gc112 -> -EL/(2*sw),
     gc113 -> EL,
     gc114 -> -(EL^3*Kw)/(4*fa*Pi^2*sw^2),
     gc117 -> -EL/(2*sw),
     gc118 -> -EL/(2*sw),
     gc122 -> -EL^2,
     gc123 -> (cw*EL)/sw,
     gc124 -> -(cw*EL^3*Kw)/(4*fa*Pi^2*sw^3),
     gc125 -> EL^2/sw^2,
     gc126R -> -ye,
     gc127 -> -((Cf*ye)/(Sqrt[2]*fa)),
     gc128R -> -ym,
     gc129 -> -((Cf*ym)/(Sqrt[2]*fa)),
     gc130R -> -ytau,
     gc131 -> -((Cf*ytau)/(Sqrt[2]*fa)),
     gc133 -> -(EL*(cw^2 + sw^2))/(2*cw*sw),
     gc134 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc135 -> (3*Ct*EL*(-kt + kV)*MT^2*Log[(16*fa^2*Pi^2)/MT^2])/(8*cw*fa*Pi^2*sw*vev),
     gc140 -> (cw*EL^2)/sw,
     gc144 -> (EL^2*(cw^2 + sw^2)^2*vev)/(2*cw^2*sw^2),
     gc145 -> -((cw^2*EL^2)/sw^2),
     gc146 -> -EL,
     gc147 -> -EL,
     gc148 -> -EL,
     gc149 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc150 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc151 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc152L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc152R -> (EL*sw)/cw,
     gc153L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc153R -> (EL*sw)/cw,
     gc154L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc154R -> (EL*sw)/cw,
     gc155 -> (2*EL)/3,
     gc156 -> (2*EL)/3,
     gc157 -> (2*EL)/3,
     gc158 -> -EL/3,
     gc159 -> -EL/3,
     gc160 -> -EL/3,
     gc161L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc161R -> (-2*EL*sw)/(3*cw),
     gc162L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc162R -> (-2*EL*sw)/(3*cw),
     gc163L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc163R -> (-2*EL*sw)/(3*cw),
     gc164L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc164R -> (EL*sw)/(3*cw),
     gc165L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc165R -> (EL*sw)/(3*cw),
     gc166L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc166R -> (EL*sw)/(3*cw),
     gc167 -> GS,
     gc168 -> GS,
     gc169 -> GS,
     gc170 -> GS,
     gc171 -> GS,
     gc172 -> GS,
     gc173 -> EL/(Sqrt[2]*sw),
     gc174 -> EL/(Sqrt[2]*sw),
     gc175 -> EL/(Sqrt[2]*sw),
     gc176 -> EL/(Sqrt[2]*sw),
     gc177 -> EL/(Sqrt[2]*sw),
     gc178 -> EL/(Sqrt[2]*sw),
     gc179 -> EL/(Sqrt[2]*sw),
     gc180 -> EL/(Sqrt[2]*sw),
     gc181 -> EL/(Sqrt[2]*sw),
     gc182 -> EL/(Sqrt[2]*sw),
     gc183 -> EL/(Sqrt[2]*sw),
     gc184 -> EL/(Sqrt[2]*sw)};

